export default {
  WORK: "/",
  SALARY: "/salary",
  ROUTES: "/routes",
  ADMIN: "/admin",
  ADMIN_FACILITIES: "/admin/facilities",
  ADMIN_FACILITY_TYPES: "/admin/facility-types",
  ADMIN_WORKERS: "/admin/workers",
  ADMIN_TASKS: "/admin/tasks",
  ADMIN_WORK_PROCESSES: "/admin/work-processes",
  ADMIN_VEHICLE_RESERVATIONS: "/admin/vehicle-reservations",
  ADMIN_VEHICLE_MANAGEMENT: "/admin/vehicle-management",
  REGISTER: "/register",
  INFO_ROAD: "/inforoad/:tg_id",
  QUESTIONNAIRE: "/questionnaire/:start_state_id",
  STOP_REASON: "/stop-reason",
  SMM_CONTENT: "/smm-content",
}